# Opt-out flag for bundling Kotlin standard library -> https://jb.gg/intellij-platform-kotlin-stdlib
kotlin.stdlib.default.dependency = false

# Enable Gradle Configuration Cache -> https://docs.gradle.org/current/userguide/configuration_cache.html
org.gradle.configuration-cache = true

# Enable Gradle Build Cache -> https://docs.gradle.org/current/userguide/build_cache.html
org.gradle.caching = true

pluginGroup = be.bruyere.romain
pluginName = Geometry Viewer
pluginRepositoryUrl = https://github.com/rombru/geometry-viewer
pluginVersion = 2025.1.0
pluginSinceBuild = 251
pluginUntilBuild = 253.*
pluginChangeNotes = Reworked the viewer integration
platformType = IC
platformVersion = 251-EAP-SNAPSHOT
platformPlugins =
platformBundledPlugins = com.intellij.java,com.intellij.platform.images